name: Bing ImmortalWrt Firmware Builder
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Firmware
        run: |
          mkdir -p bin/
          docker run --rm \
            -v ${{ github.workspace }}/bin:/home/build/openwrt/bin \
            immortalwrt/imagebuilder:x86-64 \
            bash -c "make image PACKAGES='luci-app-diskman luci-app-filebrowser luci-theme-argon luci-app-argon-config luci-app-ttyd luci-app-turboacc luci-app-openclash luci-compat kmod-tun kmod-inet-diag kmod-nft-tproxy bash curl ip-full unzip luci-app-samba4 kmod-fs-ext4'"
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: Bing-ImmortalWrt-Firmware
          path: bin/bin/targets/*/*/*
